---
- name: Apply Yum Updates
  yum:
    name: "*"
    state: latest
  register: updates_result
  
- name: Reboot Systems if Necessary
  block:
    - name: Get System Uptime
      command: uptime
      register: uptime_result

    - debug:
        var: uptime_result.stdout

    - name: Reboot Servers
      command: shutdown -r +1 "Ansible Updates Triggered" 
      become: true
      async: 0
      poll: 0

    - name: wait for webservers to reboot
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        state: started
        delay: 80
        timeout: 200
      become: false
      delegate_to: localhost
  when: updates_result.changed

- name: Get System Uptime Again to Validate Reboot
  shell: uptime
  register: uptime_result

- debug:
    var: uptime_result.stdout

- name: Install Java 1.7 and some basic dependencies
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
   - unzip
   - java-1.7.0-openjdk
   - libselinux-python
   - libsemanage-python

- name: Download JBoss from jboss.org
  get_url: 
    url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip 
    dest: /opt/jboss-as-7.1.1.Final.zip

- name: Extract archive
  unarchive: 
    dest: /usr/share 
    src: /opt/jboss-as-7.1.1.Final.zip 
    creates: /usr/share/jboss-as 
    copy: no 

- name: Cleanup previous /usr/share/jboss-as tree
  file: 
    path: /usr/share/jboss-as/ 
    owner: jboss 
    group: jboss 
    state: absent 

  # Rename the dir to avoid encoding the version in the init script
- name: Rename install directory
  command: chdir=/usr/share /bin/mv jboss-as-7.1.1.Final jboss-as creates=/usr/share/jboss-as

- name: Installing  standalone.xml Template configuration file
  template: 
    src: standalone.xml 
    dest: /usr/share/jboss-as/standalone/configuration/
  notify: restart jboss

- name: Add group "jboss"
  group: 
    name: jboss

- name: Add user "jboss"
  user: 
    name: jboss 
    group: jboss 
    home: /usr/share/jboss-as

- name: Change ownership of JBoss installation
  file: 
    path: /usr/share/jboss-as/ 
    owner: jboss 
    group: jboss 
    state: directory 
    recurse: yes

- name: Fix SELINUX Context of /usr/share/jboss-as
  command: restorecon -RF /usr/share/jboss-as

- name: RHEL6- Perform Specific Configurations
  block:
    - name: RHEL6- Copy the init script
      copy: 
        src: jboss-as-standalone.sh 
        dest: /etc/init.d/jboss 
        mode: 0755

    - name: RHEL6- Fix SELINUX Contexts /etc/init.d/jboss
      command: restorecon -RF /etc/init.d/jboss

    - name: RHEL6- Enable and Start JBoss with chkconfig and service commands
      shell: service jboss start && chkconfig jboss on

    - name: RHEL6- Enable and Start JBoss with service module
      service:
        name: jboss 
        enabled: yes 
        state: started

    - name: RHEL6- deploy iptables rules
      template: 
        src: iptables-save 
        dest: /etc/sysconfig/iptables
      notify: restart iptables
  when: ansible_distribution_major_version < "7" 

- name: RHEL7+ Perform Specific Configurations
  block:
    - name: RHEL7+ Configure the init script for systemd
      template: 
        src: jboss.systemd
        dest: /etc/systemd/system/jboss.service

    - name: RHEL7+ Fix SELINUX Contexts /etc/systemd/system/jboss.service
      command: restorecon -RF /etc/systemd/system/jboss.service
   
    #RECENTLY BROKEN systemctl managemet of jboss.  some update broke it?
    
    - name: RHEL7+ Fix jboss-as.conf issues - create /etc/jboss-as
      file: 
        dest: /etc/jboss-as
        owner: jboss
        group: jboss
        state: directory

    - name: RHEL7+ Fix jboss-as.conf issues - link /etc/jboss-as/jboss-as.conf
      file:
        src: /usr/share/jboss-as/bin/init.d/jboss-as.conf
        dest: /etc/jboss-as/jboss-as.conf
        owner: jboss
        group: jboss
        state: link

    - name: RHEL7+ Enable and Start JBoss with systemctl - RHEL7 and above
      service: 
        name: jboss 
        enabled: yes 
        state: started

    - name: RHEL7+ Ensure that firewalld is installed
      yum: 
        name: firewalld 
        state: present

    - name: RHEL7+ Ensure that firewalld is started
      service: 
        name: firewalld 
        state: started

    - name: RHEL7+ deploy firewalld rules
      firewalld: 
        immediate: yes 
        port: "{{ item }}" 
        state: enabled 
        permanent: yes
      with_items:
      - "{{ http_port }}/tcp"
      - "{{ https_port }}/tcp"
  when: ansible_distribution_major_version >= "7"
