---
- name: Copy hello-world application WAR file to host
  copy:
    src: jboss-helloworld.war
    dest: /var/tmp

- name: Copy ticket-monster application WAR file to host
  copy: 
    src: ticket-monster.war
    dest: /var/tmp

- name: Deploy HelloWorld to JBoss
  jboss:
    deploy_path: /usr/share/jboss-as/standalone/deployments/
    src: /var/tmp/jboss-helloworld.war 
    deployment: helloworld.war
    state: present
  
- name: Deploy Ticket Monster to JBoss
  jboss: 
    deploy_path: /usr/share/jboss-as/standalone/deployments/
    src: /var/tmp/ticket-monster.war 
    deployment: ticket-monster.war
    state: present

...
