---
- name: Gather EC2 facts
  hosts: "{{ ec2_hosts }}"
  gather_facts: false

  vars:
    ec2: >
      access_key="{{ ec2_access_key }}"
      region="{{ ec2_region }}"
    ec2_hosts: tag_Name_ctjon_win_wamp

  tasks:
  - name: Gather EC2 facts
    ec2_facts:

- name: Terminate EC2 hosts
  #hosts: localhost
  hosts: "{{ ec2_hosts }}"
  gather_facts: false
  connection: local

  vars:
    ec2: >
      access_key="{{ ec2_access_key }}"
      region="{{ ec2_region }}"
    ec2_hosts: tag_Name_ctjon_win_wamp

  tasks:
  - name: Terminate EC2 hosts
    ec2:
      region: "{{ ec2_region }}"
      instance_tags:
        Name: ctjon_win_web
      state: absent
      wait: True
